# Introducción

La escuela se posiciona como un actor relevante en la reproducción de la meritocracia en la socialización política de las/los estudiantes. Esto se da a partir de la educación cívica que se imparte en los colegios desde las ideas presentes en el currículo de Formación Ciudadana. De ese modo, los vínculos entre la idea del **mérito individual** y la **vida en común** se vuelven interesantes de estudiar, en tanto se traducen en una contradicción dentro de la formación de los niños y niñas que serán ciudadanos activos en sociedad en un futuro mediano. 

La *meritocracia en la escuela* se reproduce principalmente en las creencias asociadas a las prácticas que se dan en el aula. Aquello se evidencia de forma particular en la experiencia que las/os estudiantes tienen con sus notas. En ese sentido, la nota funciona como la recompensa que recibe el estudiante de acuerdo a su mérito individual. Desde ahí, se reconoce que los estudiantes emplean criterios de justicia para evaluar si sus notas recompensan de manera justa dicho mérito individual.

De forma contraria a la experiencia meritocrática que tienen los estudiantes en el aula, se presenta el rol socializador de la escuela, en tanto criterios de ciudadanía que emplea en la enseñanza sobre *Formación Ciudadana*. En este, las escuelas promueven un desarrollo sociopolítico en los jóvenes (en tanto dimensiones actitudinales, cognitivas y comportamentales), distinguiendo aspectos civiles/prosociales/comunitarios y civicos/formales, de modo que se expresa un modelo ideal de comportamiento en sociedad, entendido como una buena ciudadanía. Aquello repercute en la socialización de prácticas cohesivas en la convivencia futura que los jóvenes emplearían como ciudadanos activos en la sociedad chilena.

Con ello en mente, el presente trabajo pretende estudiar *en qué medida un sistema educativo caracterizado por una economía moral que enfatiza logros individuales es capaz de promover efectivamente los comportamientos y valores políticos y sociales asociados a los contenidos de formación ciudadana*.
